name: build navigator client (GUI)

on:
  workflow_dispatch:

env:
  BINARY_NAME: trucksim-navigator-gui
  NAV_DIR: packages/guis/navigator

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true

      matrix:
        os:
          - windows-latest
          - ubuntu-latest
          # macOS builds aren't signed, and running them without moving the quarantine flag will lead to issues with
          # Gatekeeper.
          # mac users will be encouraged to build a client from source, until i decide to cave in and sign up for an
          # Apple Developer account 😕
          - macos-latest

    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:prod -w ${{ env.NAV_DIR }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}-${{ runner.os }}-${{ runner.arch }}
          path: ${{ env.NAV_DIR }}/artifacts/*
